version: "3.9"

services:
  app:
    build: .
    container_name: car_pooling_vehicles_api
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://service-discovery:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_server:5432/vehicles_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: learnJava!2025
    networks:
      - carpooling_network

networks:
  carpooling_network:
    external: true


