version: "3.9"

services:
  app:
    build: .
    container_name: cloud-gateway-service
    ports:
      - "8888:8888"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://service-discovery:8761/eureka/
    networks:
      - carpooling_network

networks:
  carpooling_network:
    external: true
