services:

  db_server:
    image: postgres:16
    container_name: postgres_server
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: learnJava!2025
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - carpooling_network


networks:
  carpooling_network:
    name: carpooling_network
    driver: bridge

volumes:
  pg_data:
